
os: osx
language: objective-c
xcode_project: platforms/MacOS/Iota.xcodeproj
xcode_scheme: Iota
script:
  - xcodebuild -project platforms/MacOS/Iota.xcodeproj -scheme Iota -derivedDataPath 'build' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
  - find . -name "Iota*"
  - zip ./html/Iota.app.zip ./build/Build/Products/Debug/Iota.app
deploy:
  provider: pages
  verbose: true
  skip-cleanup: true
  github-token: $GITHUB_API_KEY
  keep-history: true
  local-dir: html
  on:
    branch: master

# App is in "./build/Build/Products/Debug/Iota.app"
