
os: osx
language: objective-c
xcode_project: platforms/MacOS/Iota.xcodeproj
xcode_scheme: Iota
script:
  - xcodebuild -project platforms/MacOS/Iota.xcodeproj -scheme Iota -derivedDataPath 'build' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
  - find . -name "Iota*"
  
